### PR TITLE
Add mobile presentation styles and other presentation enhancements.

### PR DESCRIPTION
**Pull request by freejoe76**

### CODE REVIEW

**Comment by tommeagher** [comment]
Joe, I love that you're still using @thunderdome-data's projects. That's fantastic. I'm sure this is all swell, but I'll ping @peggybustamante to see if she wants to give it a gander before we merge. There are obviously Post-specific styles and stuff in here, so it may not be widely reusable, but if it works for you and you're using it, great. 

One request, can you please add yourself to the credits in the README?

**Comment by freejoe76** [comment]
@tommeagher I did add the Post's trump ranker to the repo, but otherwise I kept the Post branding and stuff out of this PR. Other than the new project, I changed the names of some things to add clarity, and I changed the URL of the example project in the README (the old URL 404'ed). 

Somewhat related: Monday's my last day at the Post. I start at the end of the month up with the NY Daily News!

**Comment by freejoe76** [comment]
Okay I added myself to the credits too~~~~~

**Comment by tommeagher** [comment]
Great, Joe. Thanks, and congrats!

**Comment by peggybustamante** [comment]
Looks great, Joe. Nice to see that my ranker app is still being used. I
teach this every year to my advanced coding students, so it's nice to have
a newer example to show them.

Congrats on your new job at NY Daily News! I'm wondering if you are
replacing Evie Liu. She is one of my original break-out coding students
from USC Annenberg. She was at NY Daily News until she became a data
reporter at Dow Jones about four months ago.

Good luck!

~ @peggybustamante

**Comment by freejoe76** [comment]
@peggybustamante Hi Peggy! Hope you're doing well. I am not replacing Evie, however, once I get rolling over there I will be involved in hiring for her replacement, so if you have people you think would be good for that role let me know~~~~ joe.murphy@gmail.com

**Comment by peggybustamante** [comment]
Hi Joe! That's even better news. I definitely have people who would be good
for the role. I will send more info and names/contacts to your gmail
address. My gmail is: peggy.bustamante@gmail.com. Will you be at NICAR?

**Comment by freejoe76** [comment]
@peggybustamante Hi Peggy! I've been off github for a little bit, I'm back now, ha. I'm not sure about NICAR this year, I hope I'll be there!

**Pull request merged**
